name: /Users/n.patel/MyProj/upwork-logo-ocr/.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0
  - anyio=4.9.0
  - asttokens=3.0.0
  - attrs=25.3.0
  - beautifulsoup4=4.13.4
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.1
  - boto3=1.39.1
  - botocore=1.39.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - cairo=1.16.0
  - certifi=2025.6.15
  - cffi=1.17.1
  - charls=2.2.0
  - charset-normalizer=3.4.2
  - click=8.1.8
  - cloudpickle=3.1.1
  - cytoolz=1.0.1
  - dask-core=2024.8.0
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - docopt=0.6.2
  - easyocr=1.7.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - faiss=1.8.0
  - faiss-cpu=1.8.0
  - fastapi=0.115.14
  - fastapi-cli=0.0.7
  - ffmpeg=4.3.2
  - fontconfig=2.13.94
  - freetype=2.10.4
  - fsspec=2025.5.1
  - future=1.0.0
  - geos=3.13.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=2.9.1
  - hdf5=1.10.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=68.2
  - idna=3.10
  - imagecodecs=2021.4.28
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - ipython=8.18.1
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - jxrlib=1.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libfaiss=1.8.0
  - libffi=3.4.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libglib=2.68.4
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.29
  - libopencv=4.5.1
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.20
  - libtiff=4.3.0
  - libuv=1.51.0
  - libwebp-base=1.5.0
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=17.0.6
  - locket=1.0.0
  - lz4-c=1.9.3
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - ninja=1.12.1
  - nomkl=3.0
  - numpy=1.26.4
  - olefile=0.47
  - openblas=0.3.29
  - openblas-devel=0.3.29
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.5.1
  - packaging=25.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=25.1.1
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-opencv=4.5.1
  - pyclipper=1.3.0.post5
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytesseract=0.3.13
  - python=3.9.23
  - python-bidi=0.6.6
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.1
  - python-multipart=0.0.20
  - python_abi=3.9
  - pytorch=1.13.1
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rich=14.0.0
  - rich-toolkit=0.11.3
  - rpds-py=0.25.1
  - s3transfer=0.13.0
  - scikit-image=0.19.3
  - scipy=1.13.1
  - setuptools=80.9.0
  - shapely=2.0.7
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.45.3
  - stack_data=0.6.3
  - starlette=0.46.2
  - tifffile=2021.7.2
  - tinycss2=1.4.0
  - tk=8.6.14
  - toolz=1.0.0
  - torchvision=0.14.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-extensions=4.14.0
  - typing-inspection=0.4.1
  - typing_extensions=4.14.0
  - tzdata=2025b
  - urllib3=1.26.19
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchfiles=1.1.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websockets=15.0.1
  - wheel=0.45.1
  - x264=1!161.3030
  - xz=5.6.4
  - yaml=0.2.5
  - yarg=0.1.9
  - zeromq=4.3.5
  - zfp=0.5.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.0
