name: conda-env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pip
  - annotated-types
  - anyio
  - asttokens
  - attrs
  - beautifulsoup4
  - blas
  - blas-devel
  - bleach
  - bleach-with-css
  - blosc
  - boto3
  - botocore
  - brotli
  - brotli-bin
  - brotli-python
  - brunsli
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - coloredlogs
  - cpython
  - cytoolz
  - dask-core
  - decorator
  - defusedxml
  - dnspython
  - docopt
  - easyocr
  - email-validator
  - email_validator
  - exceptiongroup
  - executing
  - expat
  - faiss
  - faiss-cpu
  - fastapi
  - fastapi-cli
  - ffmpeg
  - fontconfig
  - freetype
  - fsspec
  - ftfy
  - future
  - geos
  - gettext
  - gettext-tools
  - giflib
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - h11
  - h2
  - harfbuzz
  - hdf5
  - hpack
  - httpcore
  - httptools
  - httpx
  - humanfriendly
  - hyperframe
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipython
  - jasper
  - jbig
  - jedi
  - jinja2
  - jmespath
  - jpeg
  - jsonschema
  - jsonschema-specifications
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jxrlib
  - krb5
  - lame
  - lcms2
  - lerc
  - libaec
  - libasprintf
  - libasprintf-devel
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcxx
  - libdeflate
  - libedit
  - libfaiss
  - libffi
  - libgettextpo
  - libgettextpo-devel
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libintl
  - libintl-devel
  - liblapack
  - liblapacke
  - libopenblas
  - libopencv
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - libuv
  - libwebp-base
  - libxml2
  - libzopfli
  - llvm-openmp
  - locket
  - lz4-c
  - markdown-it-py
  - markupsafe
  - matplotlib-inline
  - mdurl
  - mistune
  - mpc
  - mpfr
  - mpmath
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nettle
  - networkx
  - ninja
  - nomkl
  - numpy
  - olefile
  - onnxruntime
  - openai-clip
  - openblas
  - openblas-devel
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - partd
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - prompt-toolkit
  - protobuf
  - ptyprocess
  - pure_eval
  - py-opencv
  - pyclipper
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pysocks
  - pytesseract
  - python-bidi
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-flatbuffers
  - python-multipart
  - python_abi
  - pytorch
  - pywavelets
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - regex
  - requests
  - rich
  - rich-toolkit
  - rpds-py
  - s3transfer
  - scikit-image
  - scipy
  - setuptools
  - shapely
  - shellingham
  - six
  - snappy
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - starlette
  - sympy
  - tifffile
  - tinycss2
  - tk
  - toolz
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typer
  - typer-slim
  - typer-slim-standard
  - typing-extensions
  - typing-inspection
  - typing_extensions
  - tzdata
  - urllib3
  - uvicorn
  - uvicorn-standard
  - uvloop
  - watchfiles
  - wcwidth
  - webencodings
  - websockets
  - wheel
  - x264
  - xz
  - yaml
  - yarg
  - zeromq
  - zfp
  - zipp
  - zlib
  - zstd
  - pip:
      - antlr4-python3-runtime
      - colorlog
      - omegaconf
      - opencv-python
      - rapidocr
